pipeline {
    agent any

    environment {
        CUSTOM_VERSION = '1.0.0' // Define your custom version here
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install bootstrap react-bootstrap'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image with custom version and build number
                    sh "docker build -t react-app:${CUSTOM_VERSION}.${BUILD_NUMBER} -t react-app:latest redux3/"
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    def containerName = 'react-app-container'

                    // Stop and remove the existing container if it's running
                    sh "docker stop ${containerName} || true"
                    sh "docker rm ${containerName} || true"

                    // Run the Docker container with AWS CloudWatch Logs integration using custom version and build number
                    sh "docker run -dit --log-driver=awslogs --log-opt awslogs-group=my-logs-group --log-opt awslogs-create-group=true --log-opt awslogs-region=us-east-1 --log-opt awslogs-stream=${containerName}-stream -p 3000:3000 --name ${containerName} react-app:${CUSTOM_VERSION}.${BUILD_NUMBER}"
                }
            }
        }
    }
}
